apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: jenkins-server
  namespace: jenkins
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`jenkins.app.com`)
      services:
        - name: jenkins              
          port: 8080               
  tls:
    certResolver: default           
