apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
spec:
  destination:
    namespace: jenkins
    server: https://kubernetes.default.svc
  project: jenkins
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: '*'
    chart: jenkins
    helm:
      valueFiles:
        - values/jenkins-values.yaml
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
